apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001 
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
